# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2021-04-14 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='password',
            new_name='file_url',
        ),
    ]
