# Generated by Django 3.1.7 on 2021-04-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210414_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='password',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
