# Generated by Django 3.2 on 2021-04-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210422_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='Email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
